Set user environment variables by default in Windows
emscripten-core/emsdk pull request #468
Opened 2020-04-12 18:42 UTC by saschanaz

Fixes #467

This makes `./emsdk activate` to set user environment variables by default instead of previous system-wide-only activation.

Also removes some magic that implicitly nukes user envvars when system ones are shadowed, as a system admin should understand what's going on when setting envvars. Thus fixes #189 and closes #192.

2020-04-12 18:53 UTC, sbc100 commented on emsdk.py
> +def adjusted_path(tools_to_activate, log_additions=False, system=False):
Looks like the `log_additions` param is never uses, or passed.  Unrelated to this PR but since your are changing that line maybe delete it?

2020-04-12 18:59 UTC, sbc100 commented
This change looks great!

The only slight concern I have is changing the default.    Do you know that history here?  Why would setting system-wide have been desirable?  Under what circumstances would it still be desirable?  Do we need the option at all?   Maybe we simply remove the option and always set user settings?

@juj do you remember why this was done this way in the first place?

2020-04-14 14:13 UTC, juj commented
The intent of calling `emsdk activate` has been to only enable the env. vars for current/calling user prompt, not do any permanent modifications to the system.

Then, `emsdk activate --global` is intended to apply permanent modifications to "All users" section of the registry.

(The doc piece at emsdk --help looks like up to date with this respect:

```
    if WINDOWS:
      print('''
   emsdk activate [--global] [--embedded] [--build=type] [--vs2013/--vs2015/--vs2017] <tool/sdk>

                                - Activates the given tool or SDK in the
                                  environment of the current shell. If the
                                  --global option is passed, the registration
                                  is done globally to all users in the system
```

There has never existed an option to perform "Current user" only registry activation. If that is desirable, perhaps it would be good to have that as a new option `emsdk activate --local` or `emsdk activate --local_user`, instead of changing the existing `emsdk activate` from "current prompt only" to "permanent local user"?

2020-04-14 14:42 UTC, saschanaz commented
> If that is desirable, perhaps it would be good to have that as a new option `emsdk activate --local` or `emsdk activate --local_user`, instead of changing the existing `emsdk activate` from "current prompt only" to "permanent local user"?

Sorry for misleading description, but no, this doesn't change `emsdk activate` to set the permanent user global environment, instead it modifies `emsdk activate --global` to be user scope by default.

I think defaulting to user global environment is better as it does not require admin privilege.

2020-04-16 09:53 UTC, juj commented
> I think defaulting to user global environment with `--global` is better as it does not require admin privilege.

It feels like changing `--global` from meaning global to user local would be counterintuitive? A new option `--local` would be a better name?

2020-04-16 10:08 UTC, saschanaz commented
IMO it's global user variables and global system variables, not "local", which sounds like non-permanent local shell variable.

2020-04-16 16:36 UTC, sbc100 commented
I also feel like changing the meaning of an existing flag I a little confusing/misleading.    How about simply removing the old `--global` flag which is ambiguous to something more specific such as `--persistent` or `--registry`? 

Any users of the old `--global` flag could be asked to be more specific and switch to either `--persistent`  or `--persistent + --system`.

2020-04-16 16:39 UTC, saschanaz commented
`--persistent` sounds good to me, as `--global` can be an alias for `--persistent --system` then.

2020-04-17 04:39 UTC, juj commented
`--persistent` sounds good, although I would recommend instead of `--persistent --global` to have `--persistent_global`, since the flags are not orthogonal: passing `--global` on its own would not be meaningful.

2020-04-17 11:55 UTC, saschanaz commented
So does `--persistent` and `--persistent-global` sound good? Those should be mutually exclusive.

2020-04-17 15:27 UTC, sbc100 commented
I like `--persistent-system` and you could even keep the old `--global` flag as an alias to that or while/

2020-05-07 19:25 UTC, sbc100 commented
Any update on this?  I think it would be good change overall.

2020-05-07 20:43 UTC, saschanaz commented
I'll try get some time this weekend.

2020-06-23 00:21 UTC, sbc100 commented
Any update?

2020-09-15 22:39 UTC, aminya requested changes
This is a very good change. What is blocking this from merging? 

Can someone with write access update this branch?

2020-09-15 22:44 UTC, aminya commented on emsdk.py
> +  arg_system = extract_bool_arg('--system')
If `arg_system` is provided bu `arg_global` is not, it should automatically set that.
```suggestion
  arg_system = extract_bool_arg('--system')
  if arg_system
  	arg_global=True
```

2020-09-15 22:48 UTC, aminya requested changes
If there is anywhere to document the meanings of these options, we should.

```
global: set the environment variables permanently.
system: set the environment variables for all users of the system.
```

2020-09-15 22:55 UTC, sbc100 commented
`emsdk --help` is the main place we document this stuff.

2020-09-17 21:44 UTC, saschanaz commented
I have to admit that I'm not actively using emsdk nowadays. I still intend to work on it but if anyone wants to take this over, please do.

2020-09-17 21:48 UTC, sbc100 commented
No problem.  Hopefully someone can pick this up and get it landed.

2020-09-18 09:56 UTC, aminya commented
@sbc100 this is almost ready. If you have write-access why don't you just finish it?

2020-09-18 16:33 UTC, sbc100 commented
I will get around to it at some point sure, but I've got a lot of other things I'm working so if anyone else want to pick this up in the mean time feel free.

2020-09-18 22:19 UTC, aminya commented
Well, this is a critical bug on Windows, and we should fix it as soon as possible.

2020-09-30 05:15 UTC, closed without merging